@echo off
echo Updating Gallery List...

powershell -Command "$files = Get-ChildItem -Path 'image' -Include *.jpg,*.jpeg,*.png,*.gif,*.webp,*.heic,*.bmp,*.svg,*.tiff -Recurse | Sort-Object { [int]($_.BaseName -replace '\D') }; $content = '// Auto-generated by Auto-updater' + [Environment]::NewLine + 'const galleryImages = ['; $first = $true; foreach ($f in $files) { if ($first) { $content += [Environment]::NewLine + '    `'' + $f.Name + '`'' ; $first = $false } else { $content += [Environment]::NewLine + '    ,`'' + $f.Name + '`'' } }; $content += [Environment]::NewLine + '];' + [Environment]::NewLine + [Environment]::NewLine + 'window.galleryImages = galleryImages;'; Set-Content -Path 'images.js' -Value $content -Encoding UTF8"

echo Done! Images list updated.
pause
